export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const CART_SAVE_ADDRESS = "CART_SAVE_ADDRESS";
