export const REVIEWS_CREATE_REQUEST = "REVIEWS_CREATE_REQUEST";
export const REVIEWS_CREATE_SUCCESS = "REVIEWS_CREATE_SUCCESS";
export const REVIEWS_CREATE_FAIL = "REVIEWS_CREATE_FAIL";

export const REVIEWS_SEARCH_REQUEST = "REVIEWS_ALL_REQUEST";
export const REVIEWS_SEARCH_SUCCESS = "REVIEWS_ALL_SUCCESS";
export const REVIEWS_SEARCH_FAIL = "REVIEWS_ALL_FAIL";
