export const REVIEWS_SEARCH_REQUEST = "REVIEWS_SEARCH_REQUEST";
export const REVIEWS_SEARCH_SUCCESS = "REVIEWS_SEARCH_SUCCESS";
export const REVIEWS_SEARCH_FAIL = "REVIEWS_SEARCH_FAIL";

export const REVIEWS_DETAILS_REQUEST = "REVIEWS_DETAILS_REQUEST";
export const REVIEWS_DETAILS_SUCCESS = "REVIEWS_DETAILS_SUCCESS";
export const REVIEWS_DETAILS_FAIL = "REVIEWS_DETAILS_FAIL";

export const REVIEWS_CREATE_REQUEST = "REVIEWS_CREATE_REQUEST";
export const REVIEWS_CREATE_SUCCESS = "REVIEWS_CREATE_SUCCESS";
export const REVIEWS_CREATE_FAIL = "REVIEWS_CREATE_FAIL";
export const REVIEWS_CREATE_RESET = "REVIEWS_CREATE_RESET";

export const REVIEWS_EDIT_REQUEST = "REVIEWS_EDIT_REQUEST";
export const REVIEWS_EDIT_SUCCESS = "REVIEWS_EDIT_SUCCESS";
export const REVIEWS_EDIT_FAIL = "REVIEWS_EDIT_FAIL";
export const REVIEWS_EDIT_RESET = "REVIEWS_EDIT_RESET";

export const REVIEWS_DELETE_REQUEST = "REVIEWS_DELETE_REQUEST";
export const REVIEWS_DELETE_SUCCESS = "REVIEWS_DELETE_SUCCESS";
export const REVIEWS_DELETE_FAIL = "REVIEWS_DELETE_FAIL";
export const REVIEWS_DELETE_RESET = "REVIEWS_DELETE_RESET";

export const REIVEWS_VOTE_HELPFUL_REQUEST = "REIVEWS_VOTE_HELPFUL_REQUEST";
export const REIVEWS_VOTE_HELPFUL_SUCCESS = "REIVEWS_VOTE_HELPFUL_SUCCESS";
export const REIVEWS_VOTE_HELPFUL_FAIL = "REIVEWS_VOTE_HELPFUL_FAIL";
