export const REVIEWS_CREATE_REQUEST = "REVIEWS_CREATE_REQUEST";
export const REVIEWS_CREATE_SUCCESS = "REVIEWS_CREATE_SUCCESS";
export const REVIEWS_CREATE_FAIL = "REVIEWS_CREATE_FAIL";
export const REVIEWS_CREATE_RESET = "REVIEWS_CREATE_RESET";

export const REVIEWS_UPDATE_REQUEST = "REVIEWS_UPDATE_REQUEST";
export const REVIEWS_UPDATE_SUCCESS = "REVIEWS_UPDATE_SUCCESS";
export const REVIEWS_UPDATE_FAIL = "REVIEWS_UPDATE_FAIL";
export const REVIEWS_UPDATE_RESET = "REVIEWS_UPDATE_RESET";

export const REVIEWS_DELETE_REQUEST = "REVIEWS_DELETE_REQUEST";
export const REVIEWS_DELETE_SUCCESS = "REVIEWS_DELETE_SUCCESS";
export const REVIEWS_DELETE_FAIL = "REVIEWS_DELETE_FAIL";
export const REVIEWS_DELETE_RESET = "REVIEWS_DELETE_RESET";

export const REVIEWS_SEARCH_REQUEST = "REVIEWS_SEARCH_REQUEST";
export const REVIEWS_SEARCH_SUCCESS = "REVIEWS_SEARCH_SUCCESS";
export const REVIEWS_SEARCH_FAIL = "REVIEWS_SEARCH_FAIL";
