export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGN_OUT = "USER_SIGN_OUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_SECURITY_REQUEST = "USER_UPDATE_SECURITY_REQUEST";
export const USER_UPDATE_SECURITY_SUCCESS = "USER_UPDATE_SECURITY_SUCCESS";
export const USER_UPDATE_SECURITY_FAIL = "USER_UPDATE_SECURITY_FAIL";
export const USER_UPDATE_SECURITY_RESET = "USER_UPDATE_SECURITY_RESET";
